services:

  magento:
    image: docker.io/bitnami/magento:2
    container_name: magento
    privileged: true
    ports:
      - "8080:8080"
      - '8443:8443'
    environment:
      - MAGENTO_HOST=localhost
      - MAGENTO_DATABASE_HOST=mysql
      - MAGENTO_DATABASE_PORT_NUMBER=3306
      - MAGENTO_DATABASE_USER=magento
      - MAGENTO_DATABASE_NAME=magento
      - MAGENTO_ADMIN_URL_PREFIX=admin # http://localhost:8080/admin --> user:bitnami1
      - MAGENTO_EXTERNAL_HTTP_PORT_NUMBER=8080
      - ELASTICSEARCH_HOST=elasticsearch
      - ELASTICSEARCH_PORT_NUMBER=9200
      - ALLOW_EMPTY_PASSWORD=yes
      - BITNAMI_DEBUG=true
    volumes:
      - 'magento_data:/bitnami/magento'
    healthcheck:
      test: curl -f http://localhost:8080/rest
      timeout: 20s
      retries: 50
    depends_on:
      mysql:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
    labels:
      - co.elastic.logs/enabled=false
      - co.elastic.metrics/enabled=false

  mysql:
    image: docker.io/bitnami/mysql:8.0
    container_name: mysql
    volumes:
      - mysql_data:/bitnami/mysql
    ports:
      - "3306:3306"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_USER=magento
      - MYSQL_DATABASE=magento
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    labels:
      - co.elastic.logs/enabled=false
      - co.elastic.metrics/enabled=false

  phpmyadmin:
    image: phpmyadmin:5
    container_name: phpmyadmin
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - 8181:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=magento
    labels:
      - co.elastic.logs/enabled=false
      - co.elastic.metrics/enabled=false



volumes:
  mysql_data:
  elasticsearch_data:
  magento_data:
