services:

  postgresql:
    image: "postgres:14"
    container_name: postgresql
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=payments
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d postgres -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    labels:
      - co.elastic.logs/enabled=false
      - co.elastic.metrics/enabled=false

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    depends_on:
      postgresql:
        condition: service_healthy
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin@pgadmin.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin
    ports:
      - '8585:80'
    labels:
      - co.elastic.logs/enabled=false
      - co.elastic.metrics/enabled=false

volumes:
  postgres_data:
