metricbeat.modules:

- module: docker
  metricsets: ["container", "cpu", "diskio", "event", "healthcheck", "info", "memory", "network"]
  hosts: ["unix:///var/run/docker.sock"]
  period: 10s

output.elasticsearch:
  hosts: ["http://localhost:9200"]

setup.kibana:
  host: "http://localhost:5601"

setup.dashboards.enabled: true